### ISSUE TITLE
Add bestiary?

### ISSUE THREAD

**Issue by nonremittal** [Traneptora/grimoire#114]
chisaipete took down his bestiary project a few months ago. It was basically a clone of the grimoire but for monsters.

He said on Twitter that some people had cloned the project before he removed it.

Would it be possible for you (or someone else) to host/maintain it again?

**Comment by oganm** [comment]
There seems to be an up to date clone [here](https://github.com/Dr-Eigenvalue/bestiary)

**Comment by Traneptora** [comment]
I got a lot on my plate right now, including a backlog of fixes. Sorry, but not trying to bite off more than I can chew.
