### ISSUE TITLE
Suggestion: Include the TCE spell list expansions as tags

### ISSUE THREAD

**Issue by ATH1909** [Traneptora/grimoire#139]
Tasha's Cauldron of Everything has optional spell list expansions for various casting classes. For example, Augury was added to the Wizard spell list by those optional rules.

My suggestion is to add a wizard (tasha's) tag (sort of like the tags you have for spell list expansions from subclasses) or the like to spells that TCE optionally added to the Wizard spell list, and to do similar things for the other spells that got added to new lists via optional rules.

**Comment by ATH1909** [comment]
sorcerer (aberrant) and sorcerer (clockwork) tags for the spells that are on the Aberrant Mind and Clockwork Soul subclasses' default additional spells known lists would also be nice.

**Comment by Traneptora** [comment]
I'd be fine with this, but the biggest issue is I haven't yet purchased a copy of TCE. I do buy the books I use to source things but I don't have access to that one yet.

**Comment by Traneptora** [comment]
I now own a paper copy of TCE so I can look into this. Implementation is a question though. I don't like the current system with things like cleric (light) and I'd prefer to create subclass tags that inherit from the parent class. I'll have to figure it out.

**Comment by Traneptora** [comment]
I'm closing this since it's out of date with regard to the system I just created.
