### ISSUE TITLE
Spell with wrong tags

### ISSUE THREAD

**Issue by Dovahsul** [Traneptora/grimoire#143]
Hi there, I was leveling my Paladin as I saw suddenly that Warding Bond is not a full Paladin spell but a "Oath of the Crown". According to DnDBeyond, its just (Cleric, Battle Smith, Oath of the Crown, Peace Domain). Just wanted to let you know about that!

**Comment by Traneptora** [comment]
Tasha's Cauldron of Everything, page 52, adds it to the Paladin spell list.
