### ISSUE TITLE
Add Zephyr Strike

### ISSUE THREAD

**Issue by Traneptora** [Traneptora/grimoire#64]
Xanthar page 171

**Comment by AndyLampert** [comment]
Are you ok with me just posting the raw markdown in here? I'll go ahead and post my best try on this spell below, and if you're cool with this, I'll knock out the other spells similarly tomorrow. I'd really love to contribute to your project as I use it all the time, but I've long given up on pretending to be a developer so git is unfortunately beyond my ability to contribute now. 

---
layout: post
title:  “Zephyr Strike“
date:   2017-11-23
sources: [XGE.171]
tags: [ranger, level1, transmutation]
---

**1st-level transmutation**

**Casting Time**: 1 bonus action

**Range**: self

**Components**: V

**Duration**: Concentration, up to 1 minute

You move like the wind. Until the spell ends, your movement doesn’t provoke opportunity attacks.

Once before the spell ends, you can give yourself advantage on one weapon attack roll on your turn. That attack deals an extra 1d8 force damage on a hit. Whether you hit or miss, your walking speed increases by 30 feet until the end of that turn.

**Comment by Traneptora** [comment]
I'd prefer if you opened a pull request so I could comment and request changes line-by-line (for example, `Self` is capitalized). In addition, Github renders markdown in issue comments which makes copy/paste difficult.

Also, I think it's worth learning how to send pull requests anyway.

**Comment by AndyLampert** [comment]
I did learn but have since had to leave the industry and work all together due to my disabilities so I thought I'd contribute how I could. Anyway, if that's not helpful then I won't create more work for you, but if this is better than nothing I'm more than happy to knock the rest out.

**Comment by Traneptora** [comment]
I'm closing this as this has already been fixed as of now.
