### ISSUE TITLE
More of a request than issue

### ISSUE THREAD

**Issue by phl0xx** [Traneptora/grimoire#89]
Any chance the filtering and presentation could be reworked into something more like http://donjon.bin.sh/5e/spells/ or dndbeyond. It would be great to get more info on the spells displayed w/o clicking.

**Comment by Traneptora** [comment]
I'm not exactly sure what you're referring to, because the website you linked *also* requires you to click on the spells.

**Comment by Traneptora** [comment]
Information like Components or Casting Time are not super relevant to be on the main screen. Concentration might want a tag, though.

**Comment by Traneptora** [comment]
@phl0xx what exactly are you requesting? The site you linked doesn't provide much information. You still need to click on the spell to get the description.

**Comment by phl0xx** [comment]
Hi Leo!


Generally speaking:

   - More and "clickable predefined" filtering options (more on that below)
   - Sorting of columns (if the spell name, casting time etc. would be
   displayed in different columns)


With information I refer to standard information like (see below) rather
that Spell X detailed info about effect)

   - Casting Time (Ex: filter to show I listing of all, or for example
   Wizard spells that have a casting time of "reaction")
   - Range
   - Area (please have a look at dndbeyonds spell list here
   https://www.dndbeyond.com/spells
   - Spell attack (to hit) or Save (and what type of save save)
   - What type os spell is it (Utility, Damage (and type), disable,
   utility) <= This is a bit of work, not sure it's worth it

Why

   - Finding spell with certain attributes, much like the current:
   Evocation or Ritual but with more chioces, like casting time and range
   - This is great if you "do not know what specifik spell you are looking
   for"
   - Findinf the spell with a range with more than 1 mile :)
   - One of the biggest hurdles of new players in particualr is learning
   what spell do what, and even for veteran player the question "what spell
   with a casting time of "Bonus Action" do I as a druid have access to?


~peace

**Comment by Traneptora** [comment]
The issue with implementing these things is it would require a large rework of the layout of the pages. Currently the pages are very uncluttered and I like that, but turning it from a list format to a table format would definitely clutter it up. 

Not to mention that a large layout rework requires time and effort and requires me to know how to use Ruby & Jekyll, which I'm still struggling with a bit. 

Note that a large part of this functionality does come from Google. It's not perfect, but [you can try this google search](https://www.google.com/search?q=%22druid%22%20%22bonus%20action%22%20site%3Ahttps%3A%2F%2Fthebombzen.com%2Fgrimoire%2F) to find the Druid Bonus Action spells, as an example.

**Comment by phl0xx** [comment]
I understand that it would require a lot of rework. I also have no idea
what design  constraints you have etc.

Also, as you point out, the current way the spells are presented are fast,
"neat" and uncluttered wich is why we always use your site when we search
for spells :)

What prompted me to put in the request is that quite often the information
we're looking for is things like spell range or casting time :)

Maybe improving the filtering with som additional options and things like
dropdowns or checkboxes without changing the way spella are presented would
be "doable" and appreciated?


I'll try your Google search syntax example for sure!

cheers!
